
create table if not exists validation_feedback (
    id bigint generated by default as identity primary key,
    submitted_at timestamp with time zone default now(),
    respondent text,
    org_type text,
    current_method text,
    usefulness integer,
    missing_features text,
    willingness_to_test text,
    contact text
);

grant select, insert, update, delete on table validation_feedback to anon;
alter table validation_feedback disable row level security;
